### ISSUE TITLE
get-blob-metadata missing

### ISSUE THREAD

**Issue by extrawurst** [Azure/azure-sdk-for-rust#115]
When uploading a blob I can successfully upload a metadata hashmap, now I need to be able to fetch that without downloading the actual (big) blob. For this azure has the get-blob-metadata call (https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-metadata).

Can someone point me to how one approaches adding such a missing api?

**Comment by extrawurst** [comment]
thanks to #117 we can now read the metadata using `get_blob_properties`

**Comment by rylev** [comment]
@extrawurst can this be closed?

**Comment by extrawurst** [comment]
Yeah I guess but for the sake of completeness eventually adding this api makes sense I think. Would be a good place to start contributing once I get how :)

**Comment by rylev** [comment]
Leaving this open so we can make sure to implement the `get_blob_metadata` request. 

@extrawurst As @MindFlavor said, we're currently doing some big refactorings. We want to eventually move towards how the Comos crate looks like which is massively simplified. I'm going to create issues for how to help with the refactoring in case you want to help, otherwise it might be a bit confusing on where to implement this exact request.
