### ISSUE TITLE
Cosmos: Remove or change PartitionKeys type

### ISSUE THREAD

**Issue by thomastaylor312** [Azure/azure-sdk-for-rust#127]
After using the Cosmos crate for a while, I noticed that the PartitionKeys type is a bit of a pain to use. You end up with things that look like this:

```rust
&(thing.name()).into()
```

As far as I can tell, there is no technical need for this to be the type for any of these functions. It would probably be best to add more `From` implementations that don't require borrows and make the parameter use an `Into` bound (possibly reusing the readonly string type?). 

In a related note: anything that takes a `Cow` directly or a `&str` should also be changed to take something that can be `Into` for the type needed

**Comment by MindFlavor** [comment]
I agree, the `PartitionKey`s are rough to use. 

I like your idea: accepting a `Into<PartitionKeys>` will make `with_partition_keys` easier to use. 

Another approach would be to transform `PartitionKeys` into a trait and accept that. This approach will enable end user to create custom struct that can be used as partition keys (the Golang way). I personally like it because it gives freedom to the end user of the library. 

We could force early serialization in the `with_partition_keys` to avoid storing the generic in the builder. Or we we can go full ML and go for the late serialization (my personal favorite).

What do you think?
