### ISSUE TITLE
`HttpError::error_message()` is unexpectedly `None`

### ISSUE THREAD

**Issue by ahrens** [Azure/azure-sdk-for-rust#1275]
When using Azurite or the azure public cloud blob service, I am seeing `HttpError`s that have the `error_code()` filled in, but `error_message()` is None, despite the body of the response containing a Message.

I think the problem is that `http_error::get_error_message_from_body()` is assuming that the body is Json:
```rust
let json = serde_json::from_slice::<serde_json::Value>(body).ok()?;
```
However, in my experience with the Blob APIs, the body is actually XML (possibly with a BOM ([Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark))).  A [Microsoft employee explains](https://learn.microsoft.com/en-us/answers/questions/158427/does-blobstorage-api-returns-errors-in-json-format) that XML is returned even when the client requests Json.  Examples:

From Azurite (no BOM):
`StatusCode { status: 400, body: "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidQueryParameterValue</Code>\n  <Message>Value for one of the query parameters specified in the request URI is invalid.\nRequestId:dee0c303-ede6-4dab-95cd-eaaaabda595d\nTime:2023-05-11T17:12:46.001Z</Message>\n</Error>" }`
From public cloud (with BOM):
`HTTP error status (status: 404, body: "\u{feff}<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.\nRequestId:92ed15c1-901e-007b-2f90-82f3b3000000\nTime:2023-05-09T16:07:20.0241138Z</Message></Error>")`

In a previous version of the SDK, I was able to retrieve the body of the error and then parse it myself.  However, in 0.11.0, I don't see a way to get the body, except via `HttpError.to_string()`, which includes a bunch of other output and is not really intended for parsing.

FWIW, this is the code that I used to parse the body.  It would probably need to be changed to use quick-xml instead of xml-rs:
```rust
[derive(Debug, Deserialize)]
struct XmlRequestError {
    #[serde(rename = "Code")]
    code: String,
    #[serde(rename = "Message")]
    message: String,
}

                // The Byte-Order-Mark (or BOM), is a special marker added at the very beginning
                // of an Unicode file encoded in UTF-8, UTF-16 or UTF-32. It is used to indicate
                // whether the file uses the big-endian or little-endian byte order. Azure-Blob
                // returns xml with a BOM prefix. Since serde_xml_rs does not deal with it, it
                // needs to be trimmed first.
                let body = std::str::from_utf8(response.body()).unwrap();
                debug!("response body: {body}");
                if let Some(index) = body.find("<?xml") {
                    if let Ok(error) = serde_xml_rs::from_str::<XmlRequestError>(&body[index..]) {
                        return format!("{}: {}", error.code, error.message);
                    }
                }
```

I can probably open a PR to fix this, if there's agreement on the desired semantics.  Are there some responses that use Json, or do all of them use XML?  Should we try decoding as XML and if that fails then try Json?  Should we add a function to retrieve the raw body?

**Comment by merlinio2000** [comment]
@ahrens I also encountered this problem today and would be happy to fix this. Instead of trying out both methods shouldn't the `content-type` header be used to determine which encoding to try?

Also instead of writing custom XML logic, it looks to me like the [read_xml](https://docs.rs/azure_core/latest/src/azure_core/xml.rs.html#25-34) function could be used just like `from_json` currently is. 
https://docs.rs/azure_core/latest/src/azure_core/error/http_error.rs.html#124

**Comment by ahrens** [comment]
@merlinio2000 sounds good to me, thanks!

**Comment by merlinio2000** [comment]
@ahrens sorry for the delay, I finally got to it today. 

While implementing the changes I noticed a couple of files in the identity SDK that are using `ErrorKind::http_response_from_body`.

Is there any reason that `HttpError::new` couldn't be used in these places? Maybe to prevent accidentally exposing some sensitive headers the Identity endpoints require?
If the reason is similar to that then could we use `ErrorKind::http_response` and get the error code through the headers instead? I currently don't see any reason to parse the response body in these cases. [API-Guidelines error-handling](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#handling-errors)
