### ISSUE TITLE
Request builders should be more rusty

### ISSUE THREAD

**Issue by thomastaylor312** [Azure/azure-sdk-for-rust#129]
Currently the client builders are not very rust-y and they also enforce parameters at compile time. The latter is more cosmetic, but makes things less verbose. The latter leads to odd compilation errors that will likely frustrate the type of user consuming this crate (most likely an application developer). 

A concrete example of making this more rusty. 

Current:

```rust
cosmos_client
    .query_documents()
    .with_query(&Query::new(&query))
    .with_query_cross_partition(true)
    .with_parallelize_cross_partition_query(true)
    .execute()
    .await
```

Suggested:

```rust
cosmos_client
    .query_documents()
    .query_cross_partition()
    .parallelize_cross_partition_query()
    .execute(Query::new(&query))
    .await
```

The suggested idea sets options using their names and then the `execute` or `finalize` method would take the actual thing the request is acting on, be it a query or a document. 

Also, I know there is a certain architectural purity and "coolness" by having the compiler catch missing parameters. However, in my experience using this, it just leads to really weird errors that are a bit hard to figure out, especially if you are just trying to do something simple like getting a document or a blob. I suggest that we move to runtime vs compile time checks here as they will allow us to expose more specific error messages to the developer while also simplifying the builder structs and implementations.

Please note, this is not just in the cosmos crate. This pattern exists in several places and I think it should be updated everywhere

**Comment by rylev** [comment]
Before I implement this, I thought I'd try it out on one of the request builders and see how it looks. I did this on the `CreateCollectionBuilder` which is probably the most complicated builder:

## The call site

**Before**
<img width="1067" alt="Screenshot 2021-01-06 at 18 08 32" src="https://user-images.githubusercontent.com/1327285/103798736-69eeed00-504a-11eb-9fc8-17a53f975053.png">

**After**
<img width="1276" alt="Screenshot 2021-01-06 at 18 08 15" src="https://user-images.githubusercontent.com/1327285/103798765-74a98200-504a-11eb-8943-138f009400db.png">

## Error message when forgetting a required field

**Before**
Note this is at compile time
<img width="1680" alt="Screenshot 2021-01-06 at 18 12 27" src="https://user-images.githubusercontent.com/1327285/103798991-bf2afe80-504a-11eb-8788-d4ffcd227037.png">

**After**
This is at runtime.

<img width="1675" alt="Screenshot 2021-01-06 at 18 15 53" src="https://user-images.githubusercontent.com/1327285/103799315-395b8300-504b-11eb-98d0-c2602b0febc3.png">

## Docs

**Before**
<img width="539" alt="Screenshot 2021-01-06 at 18 24 17" src="https://user-images.githubusercontent.com/1327285/103800206-652b3880-504c-11eb-864a-388b9d9f6726.png">


**After**
<img width="1090" alt="Screenshot 2021-01-06 at 18 20 04" src="https://user-images.githubusercontent.com/1327285/103799773-d3bbc680-504b-11eb-87d2-f34b15b96d18.png">

## My Thoughts

I think it's clear that making these changes is worth it even if we give up a bit of compile time safety. The runtime checks will be triggered early in the dev loop and should be easy for the user to know exactly how to fix the issue (especially if we give better error messages than I did here).

**Comment by MindFlavor** [comment]
I think we are looking for a solution for the wrong problem.
The problem here is that the types are not self-explanatory: `No` and `Yes` do not help identify the issue (they would be useless even as runtime errors).

We should try to use more clear phantom types. For example instead of

```rust
CreateCollectionBuilder<Yes, No, No>
``` 

we can have

```rust
CreateCollectionBuilder<Ok, MissingIndexingPolicy, MissingOffer>
```

This way the error is clear (MissingIndexingPolicy is as clear as any runtime error) and we do not lose the compile time checks.

**Comment by rylev** [comment]
I still don't think that would help. The error would still be:

`No method for $VERY_SCARY_TYPE`

**Comment by thomastaylor312** [comment]
It also doesn't eliminate the problem discussed in #130. Most client libraries I've used in Rust and other languages don't have compile time checks. This also leads to way clearer documentation IMO, which is a huge win either way

**Comment by MindFlavor** [comment]
> I still don't think that would help. The error would still be:
> 
> `No method for $VERY_SCARY_TYPE`

True. At that point the user will look at the documentation and find out that, if they receive `MissingIndexingPolicy` it means they are missing the Indexing Policy.

The alternative is to force the user to get a runtime error (which can be complex/unlikely depending of the code), look at the error, interpret it and finally understand they are missing an IndexingPolicy. 
If they miss it - maybe just because they do not treat  the errors in a rigorous way - they end up shipping invalid code. And I mean really invalid code, that is code that will **never** work. That would be a defeat of an SDK which literally stands to avoid that.

We should ask ourselves: it's better to ship potentially invalid code that compiles or have to face errors right away - as ugly as they are? As I understand the Rust community, they prefer safety first (otherwise they would use C# or JavaScript) and they are used to complex types. 

I think we are missing two important things right now:

1. Replace `No` with a proper description.
2. Document **clearly** what the phantom types are and why they might happen.

@thomastaylor312 makes a valid point in #130, carrying around half composed builders is painful. But that's been already addressed in #119 anyway.

**Comment by thomastaylor312** [comment]
> maybe just because they do not treat the errors in a rigorous way

I understand the concern around safety, but Rust essentially forces you to handle errors by _at least_ unwrapping them or explicitly ignoring them, so an error will be seen, even if it isn't rigorously handled. Looking at common builder patterns in things like `reqwest`, `hyper`, and `std::command::Command`, we don't see validation until `build`/`finalize` is called and people safely use those all the time. I haven't personally seen (which doesn't mean it can't exist somewhere) anything mainstream that uses the style of builder as we currently have. As things currently stand there is a lot of ceremony for very little benefit IMO, particularly when trying to do the simple/common operations like fetching a document or blob. Making _every single thing_ compile time checked for me lands squarely on the dogmatic side of things rather than pragmatic.

Another option here if we are truly worried about compile time checks is to take a page from `rustoto` and have the idea of `input` and `output`, where the input structs will have required fields and everything else behind an `Option`. I don't think bespoke implementations for different sets of phantom data is developer or user friendly

**Comment by rylev** [comment]
> The alternative is to force the user to get a runtime error (which can be complex/unlikely depending of the code)

I'm all for compile time checks that can prevent **subtly** wrong code from being introduced but the errors we're discussing here are not subtle. There is no way to use these builders in *subtly* wrong ways. The user will either correctly use them or receive a panic anytime they run the code - with a very clear error message of what is wrong. This has nothing to do with what names we use for the generic parameters. This is a criticism of the mechanism itself. 

I believe our goal should be that when the user uses this API incorrectly, they are able to understand what is wrong quickly and know exactly what they need to do to fix their incorrect use. Having a compile time error will let the user know something is wrong more quickly, but that advantage is lost when it comes to having the user understand what they need to do to fix the error.

That fact, combined with the fact that the documentation is *way* more clear when the machinery for these compile time checks is removed, makes it clear to me that we should drop the compile time checks.

Again, I think having the ability to protect misusage at compile time is a great tool to have in our toolbox. I'm sure there will be times where we'll want to use it, but I don't think that this is one of those times.

**Comment by MindFlavor** [comment]
You made all valid points. And, truth to be told, the builder pattern here is really, **really** ugly 🤦‍♂️ ...

But what about going for a third way? We can switch back to the constructor pattern (like @rylev suggested some time ago).

Instead of:

```rust
client
  .create_collection()
  .with_offer(offer)
  .with_collection_name(collection_name)
  .with_partition_key(partition_key)
  .with_indexing_policy(indexing_policy)
  .execute().await?;
```

We could end up with: 

```rust
client
  .create_collection(
    offer,
    collection_name,
    partition_key,
    indexing_policy)
  .execute().await?;
```

## Benefits 

N | Benefit  | Desc
-- | -- | -- 
1 | No more ugly generics. | The type will be `CreateRequestBuilder` (eventually with lifetimes for borrows but that's it).
2 | No runtime errors. | The constructor guarantees proper initialization.
3 | Very autocompletion friendly. | 
4 | Leads to clear documentation. | The user will *read* immediately the mandatory fields as soon as they look at the `create_collection` function.
5 | Much less code in request builders. | All the `with_xxxx` mandatory function will be removed saving potentially a lot of code.

## Downsides

N | Downside | Desc
-- | -- | -- 
1 | Much less readable. | It is not a goal for our SDK so I think we can live with it. 

What do you think? I think this can be the best of both worlds.

**Comment by thomastaylor312** [comment]
Wouldn't some of the constructors get a little large? If we do go this route, I think the `Input`/`Output` structure in `rustoto` that I mentioned before might be a better pattern

**Comment by rylev** [comment]
We are only proposing doing this for the *required* parameters right? The optional ones would still be specified through builder methods? 

If so, in cosmos the largest number of required parameters is 4 which is certainly doable though I’d be a bit worried about other crates having some with more than 4.

**Comment by MindFlavor** [comment]
> We are only proposing doing this for the _required_ parameters right? The optional ones would still be specified through builder methods?

Yes only for the required params, the optional will remain as they are: there is no risk of partial construction there and they do not change the type definition. Also, the macro makes them very easy to work with.

> If so, in cosmos the largest number of required parameters is 4 which is certainly doable though I’d be a bit worried about other crates having some with more than 4.

The storage crate rewrite (#119) was done to avoid just that (and it works very well). Right now the constructors take _at most_ two parameters (which I think is acceptable) while the majority just require zero or one. This way I was able to remove all the generics while keeping the API clean. 

For example this call goes from:

```rust
let _response = client
    .put_block_blob()	
    .with_container_name(&container)	
    .with_blob_name(&blob)	
    .with_body(&buf)	
    .finalize()	
    .await?;
```

to 

```rust
let _response = blob.put_block_blob(&buf).execute().await?;
```

That's because `blob` contains both the client and the "blob name". It's an enriched client (or maybe in rusty terms we shoud call it composited client). Incidentally, it's the same thing @thomastaylor312 was doing by creating a struct that held both client and blob name.

**Comment by thomastaylor312** [comment]
I think I like this! Did this change also clean up the docs to make them more coherent?

**Comment by dmgolembiowski** [comment]
> You made all valid points. And, truth to be told, the builder pattern here is really, **really** ugly 🤦‍♂️ ...
> 
> But what about going for a third way? We can switch back to the constructor pattern (like @rylev suggested some time ago).
> 
> Instead of:
> 
> ```rust
> client
>   .create_collection()
>   .with_offer(offer)
>   .with_collection_name(collection_name)
>   .with_partition_key(partition_key)
>   .with_indexing_policy(indexing_policy)
>   .execute().await?;
> ```
> 
> We could end up with:
> 
> ```rust
> client
>   .create_collection(
>     offer,
>     collection_name,
>     partition_key,
>     indexing_policy)
>   .execute().await?;
> ```
> 
> ## Benefits
> N	Benefit	Desc
> 1	No more ugly generics.	The type will be `CreateRequestBuilder` (eventually with lifetimes for borrows but that's it).
> 2	No runtime errors.	The constructor guarantees proper initialization.
> 3	Very autocompletion friendly.	
> 4	Leads to clear documentation.	The user will _read_ immediately the mandatory fields as soon as they look at the `create_collection` function.
> 5	Much less code in request builders.	All the `with_xxxx` mandatory function will be removed saving potentially a lot of code.
> ## Downsides
> N	Downside	Desc
> 1	Much less readable.	It is not a goal for our SDK so I think we can live with it.
> What do you think? I think this can be the best of both worlds.

Hi 👋🏻 Just my two cents here.
I've found that `.map` works really well for this sort of thing (and looks pretty sweet, too).

**Comment by rylev** [comment]
I think we've found a pretty good compromise with #147. Closing this. If there's more work to do, we can open up new issues for it.
