### ISSUE TITLE
AuthorizationPermissionMismatch when including blob tags

### ISSUE THREAD

**Issue by aaronenberg** [Azure/azure-sdk-for-rust#1318]
Hi there, thanks for this awesome SDK. 

When fetching blobs with the inclusion of blob tags and authenticated by a MSI that has the role "Storage Blob Data Contributor" on both the storage account and container, I am encountering an AuthorizationPermissionMismatch error:

```
HttpError {  Status: 403,  Error Code: AuthorizationPermissionMismatch,  Body: "b"\xef\xbb\xbf<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:561892a3-701e-0024-4dd6-b8b4ad000000\nTime:2023-07-17T17:45:35.9441726Z</Message></Error>"",  Headers: [   date:Mon, 17 Jul 2023 17:45:35 GMT   x-ms-version:2019-12-12   x-ms-error-code:AuthorizationPermissionMismatch   content-type:application/xml   server:Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0   content-length:279   x-ms-request-id:561892a3-701e-0024-4dd6-b8b4ad000000  ], }
```

Here is the code that causes this error:
```rust
pub async fn get_with_tags() -> azure_core::Result<()> {
    let credentials = DefaultAzureCredential::default();
    let storage_credentials = StorageCredentials::TokenCredential(Arc::new(credentials));

    let client = ClientBuilder::new("myaccount", storage_credentials).container_client("mycontainer");

    let mut stream = client
        .list_blobs()
        .include_tags(true)
        .into_stream();
    
    while let Some(response) = stream.next().await {
        for blob in response?.blobs.blobs() {
            println!("{}", blob.name);
        }
    }
    
    Ok(())
}
```

I am able to include metadata, so I will redesign my solution to use metadata instead of tags, for now.

**Comment by krishanjmistry** [comment]
This looks like a permissions issue to me rather than an issue in the SDK. The HTTP error code you're receiving is [403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403). 
You've assigned the `Storage Blob Data Contributor` role, but from the docs it doesn't look like that has adequate permissions to access blob tags. I believe you require the `Storage Blob Data Owner` role:

> Getting blob index tags can be performed by a [Storage Blob Data Owner](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-owner) or a security principal that has been given permission to the `Microsoft.Storage/storageAccounts/blobServices/containers/blobs/tags/read` [Azure resource provider operation](https://learn.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftstorage) via a custom Azure role.

Worth reading the following two sections of the documentation:
- https://learn.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#getting-and-listing-blob-index-tags
- https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to?tabs=azure-portal#get-set-and-update-blob-index-tags

Hope this helps!

**Comment by aaronenberg** [comment]
I see. My apologies, I should have checked documentation more thoroughly. Seems odd that Storage Blob Data Contributor does not have permissions to perform actions on blob tags.
