### ISSUE TITLE
Data conversion error when using the azure_mgmt_recoveryservicesbackup crate

### ISSUE THREAD

**Issue by wbuck** [Azure/azure-sdk-for-rust#1458]
Using the `azure_mgmt_recoveryservicesbackup` version: `0.17.0` I'm receiving the following error when using the `backup_protectable_items_client` and calling the [list](https://learn.microsoft.com/en-us/rest/api/backup/backup-protectable-items/list?view=rest-backup-2023-02-01&tabs=HTTP) API endpoint:

> Error: Error { context: Custom(Custom { kind: DataConversion, error: Error("unknown variant `Microsoft.Compute/virtualMachines`, expected one of `AzureFileShare`, `AzureVmWorkloadProtectableItem`, `IaaSVMProtectableItem`", line:
 1, column: 761) }) }

The `enum` (`WorkloadProtectableItemUnion`)  in question can be found [here](https://github.com/Azure/azure-sdk-for-rust/blob/97d7e953a2f989702567504ca052d3bd114b973b/services/mgmt/recoveryservicesbackup/src/package_2023_04/models.rs#L11900C2-L11900C2).

I can see the following OpenAPI definitions for the 3 expected types in the error:

- [AzureFileShare](https://github.com/Azure/azure-rest-api-specs/blob/95c4286028ad9fecb3227288ff7345e528e7890d/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2021-02-01/bms.json#L8502)
- [AzureVmWorkloadProtectableItem](https://github.com/Azure/azure-rest-api-specs/blob/95c4286028ad9fecb3227288ff7345e528e7890d/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2021-02-01/bms.json#L8708)
- [IaaSVMProtectableItem](https://github.com/Azure/azure-rest-api-specs/blob/95c4286028ad9fecb3227288ff7345e528e7890d/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2021-02-01/bms.json#L10312C14-L10312C14)

This looks like an issue with their OpenAPI spec as I don't see a model definition with the `Microsoft.Compute/virtualMachines` `discriminator-value`.

Before I go posting an issue on their repo I wanted to confirm that the issue is indeed their specification file and not an issue with the auto generated SDK.

**Comment by krishanjmistry** [comment]
I think this is likely an issue of the auto generated SDK. @cataggar could confirm.

There is an item matching the `Microsoft.Compute/virtualMachines` that is returned by the API endpoint: [`AzureIaaSComputeVMProtectableItem`](
https://learn.microsoft.com/en-us/rest/api/backup/backup-protectable-items/list?view=rest-backup-2023-02-01&tabs=HTTP#azureiaascomputevmprotectableitem). The docs mention it is a child of [`WorkloadProtectableItem`](https://learn.microsoft.com/en-us/rest/api/backup/backup-protectable-items/list?view=rest-backup-2023-02-01&tabs=HTTP#workloadprotectableitemresource).

The `AzureIaaSComputeVMProtectableItem` is present in the REST API [here](https://github.com/Azure/azure-rest-api-specs/blob/d68618871737dc3df32655fd4235bc66a993d456/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-04-01/bms.json#L9959-L9968).

What's interesting and the cause of this is the `AzureIaasComputeVMProtectableItem` takes an allOf on the `IaaSVMProtectableItem` and which itself takes an allOf on the `WorkloadProtectableItem`. The union type is generated by only checking the first layer of allOf values rather than searching through all the layers of inheritance.

**Comment by cataggar** [comment]
Thanks @wbuck for the very detailed error. @krishanjmistry's fix will be in the next release. You can use Rust git dependency to use it now.
