### ISSUE TITLE
Make Cosmos resource models fields consistent

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#154]
Many of the resources in Cosmos share fields (e.g., `id`, `_rid`). However, sometimes we are deserializing them to different field names. For example, `_ts` is sometimes derserialized to `ts` and other times `timestamp`.

We should come up with a consistent schema for how we deserialize these resources. We should definitely make the names consistent across resources, but which field names should we pick?
Questions:

* Should the fields be left as they are in the response json?
* If not, should they simply be renamed to remove the leading `_`?
* if not, should they be renamed to more descriptive names (e.g., `timestamp` instead of `ts`)?

**Comment by MindFlavor** [comment]
I would prefer to leave as they are in the JSON (since we adhere fairly closely to the REST API). Unfortunately in rust the underscore has syntactical meaning so it can lead to confusion or, worse, bugs.

I've looked at the C# SDK and they leave the choice to the caller ([https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readitemasync?view=azure-dotnet#remarks](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readitemasync?view=azure-dotnet#remarks)). I do not particularly like this: for one, the `id` is treated differently. Also the `etag` is necessary for optimistic concurrency (a big deal in transactionless databases). I'd rather always have it handy,. especially since the API always return it (and I don't like to throw away stuff 🤷‍♂️). 

That said, I'm really on the fence on this. 
I'd say let's go with `ts`, `etag` and `ttl`. They are close to what the other API use but do not lead to errors in rust.

**Comment by rylev** [comment]
I'm fine with that. We should just ensure that the documentation is good and explicitly states what the (sometimes cryptically named) fields actually represent.

**Comment by rylev** [comment]
The generated mimics the names exactly. Perhaps removing the leading `_` is possible and would be easy to also do in generated code.
