### ISSUE TITLE
Can't build `azure_storage` without default features or combinations of features less than the default

### ISSUE THREAD

**Issue by carols10cents** [Azure/azure-sdk-for-rust#177]
## What happened

I'm trying to test out [this PR](https://github.com/Azure/azure-sdk-for-rust/pull/176), and in the project where we're using `azure_storage`, we had specified it as `default-features = false, features = ["table", "blob"]`.

If I check out either the issue/175/pr branch at 7cc0997 or the master branch at dbc74334 and try to build just the azure_storage crate, the following commands result in compiler errors:

```
$ cargo build --no-default-features
...
error: aborting due to 93 previous errors
```

```
$ cargo build --no-default-features --features blob
...
error: aborting due to 16 previous errors
```

```
$ cargo build --no-default-features --features table
...
error: aborting due to 85 previous errors
```

```
$ cargo build --no-default-features --features account
...
error: aborting due to 93 previous errors
```

```
$ cargo build --no-default-features --features queue
...
error: aborting due to 85 previous errors
```

Some combinations, like `table,blob`, also don't work. I haven't checked all combinations. `table,blob,queue` *does* work, as does using the default feature set of `account,blob,queue,table`

## What I expected

[The current README for `azure_storage`](https://github.com/Azure/azure-sdk-for-rust/blob/dbc74334a241fb38f7fcb6e28af50b58cacd4e93/sdk/storage/README.md) seems to indicate I should be able to turn off default features and only turn on the ones I'm using, which sounds like each feature should be independent and any combination should compile.

I realize the crate is still going through a lot of reorganization, but I'm wondering what the eventual intent is. In other words, is it the code or the documentation that needs to be fixed?

**Comment by MindFlavor** [comment]
Hi @carols10cents!
we eventually want to be able to compile different features independently (or at least have a meaningful subset of independent features). 

Right now there is still a lot of cruft accumulated in years of code (not to mention, different versions of Rust and its libraries) so we are nowhere near reaching that goal. For example, we plan to remove any dependency from HTTP client crates from SDK's ancillary crates: they should only reference the `azure_core::HTTPClient` trait. In order to do so we need to migrate the old trait-based code that we decided was too convoluted. 
Once done for every ancillary crate we can make sure every feature compiles on its own. 

Thank you for point this out though, we definitely need to track it!
