### ISSUE TITLE
Support for ExpiryOptions on BlobStore requests

### ISSUE THREAD

**Issue by JensWalter** [Azure/azure-sdk-for-rust#291]
I tried setting the expiry option on some blob store request, but I could not find the appropriate way to do so.

Setting an expiration is described in the official documentation:
https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-expiry

So far I could not figure out how I could send such options. I tried setting those parameters through the metadata field, but this lead to the following result.
```
let mut metadata = Metadata::new();
metadata.insert("x-ms-expiry-time".to_string(), "300000".to_string());
metadata.insert("x-ms-expiry-option".to_string(), "RealtiveToCreation".to_string());
let res = container
  .as_blob_client(blob_key)
  .put_block_blob(blob_data.clone())
  .content_type("text/plain")
  .hash(&hash)
  .metadata(&metadata)
  .execute()
  .await.unwrap();
```
The header was transformed into 
```
  headers: {
    "content-length": "181",
    "x-ms-blob-type": "BlockBlob",
    "content-md5": "cew9Xo2MS8dQ+UyCtsta3w==",
    "content-type": "text/plain",
    "x-ms-meta-x-ms-expiry-option": "RealtiveToCreation",
    "x-ms-meta-x-ms-expiry-time": "300000",
    "x-ms-date": "Fri, 11 Jun 2021 15:23:19 GMT",
    "x-ms-version": "2019-12-12",
    "authorization": "SharedKey ******",
  },
```

What would be the correct way to set the expiration?
If this feature does not yet exist, what would be the best approach integrating this into the sdk?

**Comment by MindFlavor** [comment]
Hi @JensWalter, no, the blob expiry is not currently supported by the SDK. The expiry feature is available since version 2020-02-10 but the SDK still targets 2019-12-12 as defined here: https://github.com/Azure/azure-sdk-for-rust/blob/fb5598b48d7523804c712d7ac5f6e0b5aa9f2066/sdk/storage/src/core/clients/storage_account_client.rs#L20

The `metadata` function you are using is related to this feature: [set-blob-metadata](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata). This basically attaches arbitrary key-value pairs to a blob. That's why your headers get mangled.

While there is no way to customize the service level nor pass extra headers right now, we are currently migrating to a pipeline-based approach that will be less strict, possibly allowing users to fully customize the headers sent to Azure.

**Comment by JensWalter** [comment]
OK, thanks for the explanation.
So I will wait for the necessary migrations to happen first.

Let me know when I can help in any way to get this into the SDK.

**Comment by bmc-msft** [comment]
Support for blob expiry was added in #913
