### ISSUE TITLE
Consider adding a bot for helping merge PRs

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#463]
The SDK project contains a lot of different (and often times completely separate crates). We may want to consider adopting something like @bors which can allow more fine grained CI test running. This would allow for instance that only handwritten SDK tests get run on each push, and the full CI run (including services which take quite a while) gets run before merging.

**Comment by yoshuawuyts** [comment]
We could probably apply for the [Github Merge queue beta](https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta/) which provides bors-like functionality built directly into GitHub.

**Comment by heaths** [comment]
I'd recommend we not diverge from what our central EngSys team managers for other repos if this repo has a chance of being official. We set up pipelines per-service directory e.g., `sdk/keyvault` with appropriate triggers, except for `azure_core` which runs them all since its core to the rest of the crates.

/cc @weshaggard

**Comment by cataggar** [comment]
Not currently planned.
