### ISSUE TITLE
Decide on a way to configure base URL (aka cloud location)

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#466]
We currently don't have a universal way for declaring which version of Azure a client will talk to. The following ways are currently used:

* Cosmos Client [formats URL on every request](https://github.com/Azure/azure-sdk-for-rust/blob/4c23d89980922be659a05e70c0fb094a4bde7173/sdk/cosmos/src/clients/cosmos_client.rs#L326) using CloudLocation abstraction and doesn’t attempt to make sure it’s a valid URL
* Storage Account Client [formats URL during construction](https://github.com/Azure/azure-sdk-for-rust/blob/4c23d89980922be659a05e70c0fb094a4bde7173/sdk/storage/src/core/clients/storage_account_client.rs#L91), parses it to check correctness, and panics on ParseError
* Data Lake Client [formats the URL during construction](https://github.com/Azure/azure-sdk-for-rust/blob/4c23d89980922be659a05e70c0fb094a4bde7173/sdk/storage/src/data_lake/clients/data_lake_client.rs#L104), and returns a result with ParseError
* The Data Laka Client in the .Net SDK doesn’t deal with formatting or parsing at all, it just [takes a full Uri during construction](https://github.com/Azure/azure-sdk-for-net/blob/7cc705d20ce5866f5c9673ec2f330dc417059f62/sdk/storage/Azure.Storage.Files.DataLake/samples/Sample02_Auth.cs#L49)

This was also discussed [here](https://github.com/Azure/azure-sdk-for-rust/pull/457#discussion_r738564089).

We should decide on one approach and stick to it.

The first approach used in Cosmos seems like the best option to me. It doesn't require the user to send the entire URL which is largely the same for every single user, only the part that differs (the account name).

**Comment by heaths** [comment]
As @JeffreyRichter mentioned, account names are too restrictive when it comes to other cloud environments like USGov or Mooncake. All our official SDKs take a URI (as a string or otherwise), and API versions - if not part of the URI (not recommended for services, but a few do but should be migrating away) should be part of the optional options passed to the client. We had previously talked about a `with_options()` function to take an options, but if it's more idiomatic to have setters for individual properties of the client that could work as well, though the client options pattern I've already added to the repo is what I suggest we use, which allows "inheriting" default pipeline options like pipeline policies.

**Comment by heaths** [comment]
It came up in our v-team meeting today about api-versions - specifically shipping support for multiple versions. While most of our official SDKs don't and we probably want to follow suit for the Unofficial Azure SDK for Rust to use only the latest api-version (see #726), we still need to discuss how this will look in Rust. For example,

```rust
let options = ClientOptions::new()
  .with_api_version("2022-05-01");
```

Ideally we have some enum of these values so it's more discoverable.

Because of our strict [Breaking Changes policy (internal)](https://aka.ms/AzBreakingChangesPolicy) it's very unlikely targeting latest will be a problem. It hasn't been in other SDKs, and only recently have we even started to use the specified api-version to bifurcate endpoints and, maybe, de/serialization (still being considered).

We should also follow the same pattern we use for other SDKs:

1. While a REST API is in preview, our SDKs are beta (we specifically use "beta" to avoid confusion with "preview" of the service, which carries certain responsibilities).
2. When a REST API GA's (stable directory), we GA the SDK.
3. At a minimum we require 1 week to generate, updated, and release an SDK from either a preview or stable swagger.
4. We can still use feature branches (or release branches, whatever you'd like to call them) to stabilize. Our central EngSys support a `release/` branch prefix and can do release builds from there. We generally stabilize in a `release/` branch and continue with parallel development in `main`.

**Comment by simon-an** [comment]
Any news on this? Hard coded urls (storage account) make it currently impossible to write tests with mockito by just setting the domain to localhost.
