### ISSUE TITLE
Enable E2E tests in CI pipeline

### ISSUE THREAD

**Issue by MindFlavor** [Azure/azure-sdk-for-rust#49]
Some crates have E2E tests in addition to local ones. These tests ensure the correctness of the implemented APIs by checking them against the Azure platform. 
We have to decide if it makes sense to reenable these tests in the current CI pipeline.

PS: We can kick off the tests with `cargo test --features=test_e2e` in the supported modules.

**Comment by rylev** [comment]
I don't think e2e tests make sense since most of them require an active Azure subscription to run. We are now checking that the tests actually compile. Perhaps we can consider a bors style PR merger at some point, that allows us to kick off e2e tests manually through the GitHub PR interface, but I think it would be a very bad idea to run these tests automatically.

**Comment by MindFlavor** [comment]
Yes it's a good idea. 
The problems are that the E2E tests are, now, neither idempotent nor resilient. 
That means that a failed test leaves the subscription in an undetermined state possibly causing subsequent tests to fail. 
Also, sometimes Azure services return a transient error that could make the test fail even if they should not. 

Until those two problems are fixed I believe your approach is the best. 👍
