### ISSUE TITLE
Rust newbie experience problems with the SDK

### ISSUE THREAD

**Issue by AdamGlass** [Azure/azure-sdk-for-rust#700]
From a relative rust newbie:

* [ ] Nothing in the github README points me to any get started information
* [x] Nothing in the azure svc generated crates points me back to the github stuff for documentation
* [ ] Nothing tells me upfront that the SDK is async.  It was only when i saw the examples with the tokio directive on main that i learned this.  I think async is a new feature in the python sdk so i was surprised actually to see it here. 
* [x] I would've benefited from the the SDK consumer version of this file : https://github.com/Azure/azure-sdk-for-rust/blob/e20527c8d14f029c43f39a6034762facc608d293/services/api-versions.md which tells me about how you can choose an api-version via cargo.toml features .  Maybe this should be in each generated service crate. 
* [ ] More highlighting of the credential/identity flow stuff since the crates almost all have a requirement on using azure-identity to get a credential.
* [ ] For the generated SDKs, i wonder if its worth having a pointer back to the REST content which sometimes has better explanations.
* [ ] Lesser desire: some way to get the actual request that was sent or was going to be sent.
* [x] All the svc examples would benefit from a link to the existing services examples.
* [x] All the svc examples use methods with no arguments or very few.  eg. list or create.  a more complex example of a service that takes a more complex struct etc. might be worthwhile.  Even if you don't do the builder thing, you could still maybe have one that does the ', ..Default::default()} thing for structure initialization.

**Comment by cataggar** [comment]
Thanks for the feedback @AdamGlass! For today, I'd like to focus on the last two since I am pretty close to publishing version 0.2 of the service crates.

> All the svc examples would benefit from a link to the existing services examples.

I've added readmes for all the services. Can you open a PR with changes to this template?
https://github.com/Azure/azure-sdk-for-rust/blob/main/services/autorust/codegen/templates/readme.md.jinja

> All the svc examples use methods with no arguments or very few. eg. list or create. a more complex example of a service that takes a more complex struct etc. might be worthwhile. Even if you don't do the builder thing, you could still maybe have one that does the ', ..Default::default()} thing for structure initialization.

The [create_task](https://github.com/Azure/azure-sdk-for-rust/blob/main/services/svc/batch/examples/create_task.rs) example is probably the best for this. It has:

``` rust
    let pool_info = PoolInformation {
        pool_id: Some(pool_id),
        ..PoolInformation::new()
    };
```

So it is covered, but only in one example. We welcome more examples.

**Comment by aeshirey** [comment]
I'd like to pile on some of the pain points I'm hitting (specifically, I'm using blob storage functionality), with apologies in advance that these are not small and I'm not exactly helping out with resolution. FWIW, I have some Rust experience but no familiarity with other Azure SDKs:

- [ ] Crate documentation says to use the git version, which seems like a dangerous proposition. I should be able to reliably use, eg, `azure_storage_blobs = "0.1.0"`, not `azure_storage_blobs = { version = "0.1.0", git = "https://github.com/Azure/azure-sdk-for-rust" }`
- [ ] To get something working, it seems it's necessary to select multiple crates:
  ```toml
  azure_core = { version = "0.2.1", git = "https://github.com/Azure/azure-sdk-for-rust" }
  azure_storage = { version = "0.1.0", git = "https://github.com/Azure/azure-sdk-for-rust" }
  azure_storage_blobs = { version = "0.1.0", git = "https://github.com/Azure/azure-sdk-for-rust" }
  ```
  If I accidentally mix and match crates.io and git, I get version mismatches. Is there a reason we can't convert individual crates to optional features? eg, `azure_sdk = { version = "x.y", features = ["storage"] }`
- [ ] Doc comments are almost entirely nonexistent, which is a huge blow to discoverability. I can execute a `BlobClient`'s `.put_block_blob()` without errors, but it does nothing; `.put_block()` works as expected, but as a crate user, I'm accustomed to understanding the API directly from the code.
- [ ] Since I can't grok the API from doc comments, I tried looking up [the docs corresponding to blob storage functions](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block), but it's not 1:1 (again, `.put_block_blob()` is a problem. This is effectively' a +1 to @AdamGlass's sixth comment, but also the existing functions seem to not match up to what documentation says.

**Comment by gzp-crey** [comment]
> To get something working, it seems it's necessary to select multiple crates

Would it be possible to create an azure crate that includes all the others and using features they could be turned on ?
The crate would just simpl ereexport the others for example:
azure_core -> azure::core
azure_storage -> azure::storage
azure_storage_blobs -> azure::storage::blobs or azure::storage_blobs

**Comment by cataggar** [comment]
Thank you for the feedback.
