### ISSUE TITLE
Examples for storage_blobs show methods that don't exist

### ISSUE THREAD

**Issue by jakerieger** [Azure/azure-sdk-for-rust#918]
I'm trying to create a client to connect to Azure Blob Storage. All of the examples show this line for creating the client:

```rust
let storage_client = StorageClient::new_access_key(&account, &access_key);
```

However, `StorageClient::new_access_key` doesn't exist. You can verify this on the docs page for the StorageClient struct here: [https://docs.rs/azure_storage/0.4.0/azure_storage/core/prelude/struct.StorageClient.html#impl](https://docs.rs/azure_storage/0.4.0/azure_storage/core/prelude/struct.StorageClient.html#impl)

Same goes for the `StorageClient::new_connection_string` method as well.

Actually, most of the methods shown in the example as members of the `StorageClient` struct don't actually exist. Am I missing something here?

**Comment by rylev** [comment]
Sorry for the confusion. This is a result of the fact that what's on the main branch in this repo, has not yet been released to crates.io. You have a few options here: 
* Use the `azure_storage_blobs` crate as a git dependency so that the code you're using matches what's on the main branch.
* Look at the old examples [here](https://github.com/Azure/azure-sdk-for-rust/tree/c5e1af26ae19957a92cf0d154174b8b247fc6a73) from right when the new release was cut. 

I hope this helps. Hopefully, we release a 0.5 version of the crate soon which will make the examples line up with what's on crates.io again.

**Comment by jakerieger** [comment]
Ah that makes sense. Thanks for the response
