### ISSUE TITLE
Cosmos: Why use dyamic dispatch for CollectionName, DatabaseName, UserName, etc.

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#96]
Currently there are several traits for indicating how to get the name of different resources. These are usually used in a dynamic dispatch way (e.g., `fn foo(name: &dyn DatabaseName)`). Since the only thing that these traits allow you to do is to get a string slice whose lifetime is tied to the borrow of the trait object, I don't really see a need for the trait object indirection. Can these trait objects be removed and simply replaced with string slices?

**Comment by rylev** [comment]
@MindFlavor, this is likely a question your best qualified to answer 😊

**Comment by MindFlavor** [comment]
IIRC it was done because an user requested it. 
The user wanted to be able to use arbitrary structs as permission, database, collection, etc... so we created a trait for each. As long as the struct implemented the correct trait it works.

For example, suppose we have different collections and need to route a document into the right collection. If the document implements `CollectionName` it would be something easy like `client().with_collection(&doc).insert_document(&doc)`. And the "routing" code would be close to the actual document. 

The same logic applies for user name and permission: if someone has a "user" struct, implementing `UserName` (which would probably be a one-liner) makes this explicit and allows for the above pattern.

That said, as of now the traits do not give any additional benefit. We should at least add some kind of runtime/compile-time validation (ie not all str are valid database names).

We can switch to `str`, it's a design choice. 

I would not chose based on the performance loss. Dynamic dispatch cost is practically negligible ([http://jamesmcm.github.io/blog/2020/07/25/intro-dod/](http://jamesmcm.github.io/blog/2020/07/25/intro-dod/)). 

The downside of trait objects is that it does not work if the struct cannot be a trait object.

**Comment by rylev** [comment]
Thanks for the context. I'll take a look at improving #97 so that we don't just remove the traits, but actually build in some correctness guarantees.

**Comment by MindFlavor** [comment]
I think we can close this, the traits have been phased out with the current, more elegant solution.
